name: Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.action == ''
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Docker Registry
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u lucasl0st --password-stdin
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ghcr.io/lucasl0st/collector:latest

      - name: Delete old versions from GHCR
        uses: actions/delete-package-versions@v4
        with:
          package-name: collector
          package-type: container
          delete-only-untagged-versions: true
          token: ${{ secrets.GHCR_TOKEN }}